#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#define FORECOLOR_BLACK "\x1b[30m"
#define FORECOLOR_YELLOW "\x1b[33m"
#define FORECOLOR_WHITE "\x1b[37m"
#define FORECOLOR_GREEN "\x1b[32m"
#define BACKGROUNDCOLOR_BLACK "\x1b[40m"
#define BACKGROUNDCOLOR_WHITE  "\x1b[47m"
#define BACKGROUNDCOLOR_YELLOW "\x1b[43m"
#define COLOR_RESET "\x1b[0m"
int main(){
  printf("/‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾\\\n");
  FILE *p;
  int ch;
  int contador = 0;
  int animar = 0;
  p = popen("fortune brasil", "r");
  while ((ch = fgetc(p)) != EOF){
      if (ch != '\t'){
          if (contador >= 80 && ch != '\n'){
              putchar('\n');
              contador = 0;
          }
          else if (ch == '\n'){
              putchar('\n');
              contador = 0;
          }
          else{
              putchar(ch);
              contador++;
          }
      }
  }
  printf(FORECOLOR_GREEN "A Propósito, Bem Vindo!" COLOR_RESET);
  printf("\n\\_____________________________________________________________________________/\n             /");
  printf("\n" "     " FORECOLOR_BLACK "◢" COLOR_RESET BACKGROUNDCOLOR_BLACK "   " COLOR_RESET FORECOLOR_BLACK "◣" COLOR_RESET " /" "\n" "     " BACKGROUNDCOLOR_BLACK " " COLOR_RESET BACKGROUNDCOLOR_WHITE FORECOLOR_BLACK "●" COLOR_RESET BACKGROUNDCOLOR_BLACK FORECOLOR_YELLOW "▄"  COLOR_RESET BACKGROUNDCOLOR_WHITE FORECOLOR_BLACK "●" COLOR_RESET BACKGROUNDCOLOR_BLACK " "  COLOR_RESET "\n" "     " BACKGROUNDCOLOR_BLACK " " COLOR_RESET BACKGROUNDCOLOR_YELLOW  FORECOLOR_BLACK "──/" COLOR_RESET BACKGROUNDCOLOR_BLACK " " COLOR_RESET "\n" "    " FORECOLOR_BLACK "◢" COLOR_RESET BACKGROUNDCOLOR_BLACK " " COLOR_RESET BACKGROUNDCOLOR_WHITE "   " COLOR_RESET BACKGROUNDCOLOR_BLACK " " COLOR_RESET FORECOLOR_BLACK "◣" COLOR_RESET "\n" "   " FORECOLOR_BLACK "◢" COLOR_RESET BACKGROUNDCOLOR_BLACK " " COLOR_RESET BACKGROUNDCOLOR_BLACK FORECOLOR_WHITE "◢" COLOR_RESET BACKGROUNDCOLOR_WHITE "   " COLOR_RESET BACKGROUNDCOLOR_BLACK  FORECOLOR_WHITE "◣ " COLOR_RESET FORECOLOR_BLACK "◣" COLOR_RESET "\n" "  " FORECOLOR_BLACK "◢" COLOR_RESET BACKGROUNDCOLOR_BLACK " " FORECOLOR_WHITE "◢" COLOR_RESET BACKGROUNDCOLOR_WHITE "     " COLOR_RESET BACKGROUNDCOLOR_BLACK FORECOLOR_WHITE "◣ " COLOR_RESET FORECOLOR_BLACK "◣" COLOR_RESET "\n" " " FORECOLOR_YELLOW "◢" COLOR_RESET BACKGROUNDCOLOR_YELLOW " " COLOR_RESET BACKGROUNDCOLOR_BLACK " " COLOR_RESET BACKGROUNDCOLOR_WHITE FORECOLOR_BLACK "◣" COLOR_RESET BACKGROUNDCOLOR_WHITE FORECOLOR_YELLOW "     ◢" COLOR_RESET BACKGROUNDCOLOR_BLACK "  " COLOR_RESET FORECOLOR_YELLOW "◣" COLOR_RESET "\n" BACKGROUNDCOLOR_YELLOW "     " COLOR_RESET BACKGROUNDCOLOR_WHITE FORECOLOR_YELLOW "◣" COLOR_RESET BACKGROUNDCOLOR_WHITE "   "  FORECOLOR_YELLOW "◢" COLOR_RESET BACKGROUNDCOLOR_YELLOW "     " COLOR_RESET "\n" FORECOLOR_YELLOW "▀▀▀▀▀▀" COLOR_RESET FORECOLOR_BLACK "▀▀▀" COLOR_RESET FORECOLOR_YELLOW "▀▀▀▀▀▀" COLOR_RESET "\n" "              ");
  return 0;
}
